import type { BrandConfig } from "@/lib/types";

export const brands: BrandConfig[] = [
  {
    id: "twinings",
    name: "Twinings",
    collectionUrl: "https://twiningsusa.com/collections/all-teas",
    type: "paginated",
    productLinkSelector: ".product-card a",
    nextPageSelector: ".pagination__next",
    maxProducts: 25,
    delayMs: 1500,
  },
  {
    id: "bigelow",
    name: "Bigelow",
    collectionUrl: "https://www.bigelowtea.com/collections/all",
    type: "shopify",
    productLinkSelector: ".product-item-meta__title",
    maxProducts: 20,
    delayMs: 1200,
  },
  {
    id: "twg",
    name: "TWG",
    collectionUrl: "https://twgtea.com/en/find-a-tea/loose-leaf-teas/by-predominant-flavours/floral",
    type: "js-rendered",
    productLinkSelector: "a[href*='/loose-tea/']",
    maxProducts: 20,
    delayMs: 2000,
  },
  {
    id: "harney",
    name: "Harney & Sons",
    collectionUrl: "https://www.harney.com/collections/all",
    type: "shopify",
    productLinkSelector: ".product-card a, .grid-product__link",
    maxProducts: 20,
    delayMs: 1200,
  },
  {
    id: "pukka",
    name: "Pukka Herbs",
    collectionUrl: "https://www.pukkaherbs.com/us/en/herbal-teas.html",
    type: "js-rendered",
    productLinkSelector: "a.product-detail",
    maxProducts: 15,
    delayMs: 1500,
  },
  {
    id: "vahdam",
    name: "Vahdam",
    collectionUrl: "https://www.vahdam.com/collections/all",
    type: "shopify",
    productLinkSelector: ".product-card a, .grid-product__link",
    maxProducts: 15,
    delayMs: 1200,
  },
  {
    id: "yogi",
    name: "Yogi Tea",
    collectionUrl: "https://yogi-life.com/en-US/product/product-types/hot-tea",
    type: "js-rendered",
    productLinkSelector: "a[href*='/en-US/product/']",
    maxProducts: 15,
    delayMs: 2000,
  },
  {
    id: "rishi",
    name: "Rishi Tea",
    collectionUrl: "https://www.rishi-tea.com/collections/all-teas",
    type: "shopify",
    productLinkSelector: ".product-card a, .grid-product__link",
    maxProducts: 12,
    delayMs: 1200,
  },
  {
    id: "teekanne",
    name: "Teekanne",
    collectionUrl: "https://www.teekanne.com/products/",
    type: "js-rendered",
    productLinkSelector: "a.product-teaser__link",
    maxProducts: 10,
    delayMs: 2000,
  },
  {
    id: "marketspice",
    name: "MarketSpice",
    collectionUrl: "https://www.marketspice.com/collections/teas",
    type: "shopify",
    productLinkSelector: ".product-card a, .grid-product__link",
    maxProducts: 5,
    delayMs: 1200,
  },
  {
    id: "hawaiian-islands",
    name: "Hawaiian Islands Tea",
    collectionUrl: "https://www.hawaiianislandstea.com/shop-tea/",
    type: "js-rendered",
    productLinkSelector: "a[href*='/shop-tea/']",
    maxProducts: 3,
    delayMs: 1200,
  },
];

export function getBrandById(id: string): BrandConfig | undefined {
  return brands.find((b) => b.id === id);
}
